### PR TITLE
Add dependabot.yml

### PR DESCRIPTION
**Pull request by DeepDiver1975**
See in my fork how dependabot updates dependencies - especially the guzzle update is critical ...

THX

### CODE REVIEW

**Comment by DeepDiver1975** [comment]
@eropple allow me to ping you on this PR as you are the one who touched composer.* last

THX

**Comment by jsanford8** [comment]
Hi @DeepDiver1975 - thank you for the PR here! We're actually in the process of using another service (used across Mux) for dependency management and monitoring, so in lieu of that work, I'm going to close out this PR. We'll work to get that in as soon as we can, and thanks again!

**Comment by DeepDiver1975** [comment]
@jsanford8 THX for your feedback - any chance to get the dependencies updated - kind of asap aka now ;-)

guzzle http is pinned to [7.4.2](https://github.com/muxinc/mux-php/blob/b76cf98f8f24b26070b1ceb4a09205e3f67309c0/composer.lock#L11) which has vulnerabilities refs https://packagist.org/packages/guzzlehttp/guzzle/advisories?version=6078636

THX a lot

**Comment by jsanford8** [comment]
Absolutely. We'll try to get this out this week or early next week, sorry for the inconvenience!

**Comment by jaredsmith** [comment]
Can you please try the latest 3.7.0 release (just released this afternoon), and let me know if that fixes things for you in the short term?

**Comment by DeepDiver1975** [comment]
> Can you please try the latest 3.7.0 release (just released this afternoon), and let me know if that fixes things for you in the short term?

sure - once it is available on https://packagist.org/packages/muxinc/mux-php

**Comment by DeepDiver1975** [comment]
Looks good - THX a lot! :+1:

**Pull request closed without merging**
